# Generated by Django 4.2 on 2023-04-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_password_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_reset_token',
        ),
    ]
