# Generated by Django 4.2 on 2023-04-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
