# Generated by Django 4.2.1 on 2023-05-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_user_is_subscribed_delete_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='num_of_national_election_voted',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Number of national elections voted in'),
        ),
        migrations.AddField(
            model_name='user',
            name='num_of_state_election_voted',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Number of state elections voted in'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='political_affiliation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
