# Generated by Django 4.2.1 on 2023-05-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_user_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('Liberty plan', 'Liberty plan'), ('Patriot plan', 'Patriot plan'), ('Eagle plan', 'Eagle plan'), ('Stars and Stripes plan', 'Stars and Stripes plan'), ('Founding Fathers plan', 'Founding Fathers plan')], max_length=30, null=True),
        ),
    ]
