# Generated by Django 4.2.1 on 2023-05-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_fee',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
