# Generated by Django 4.2.1 on 2023-05-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=250, null=True)),
                ('author_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Author title')),
                ('blog_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Blog title')),
                ('body', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog')),
            ],
        ),
    ]
